name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v2.3.4

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '14'

    - name: Cache Node modules
      uses: actions/cache@v2.1.3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install
      
    - name: Run linters
      run: npm run lint

    - name: Build the component
      run: npm run build

    - name: Execute all tests
      run: npm run test
